### ISSUE TITLE
Every command slowed 5s by `socket.getfqdn` on Mac

### ISSUE THREAD

**Issue by patrickmineault** [mila-iqia/milatools#49]
On my Mac, on my home wifi, with the latest version of the tools, it takes about 5 seconds for the call to `mila` to respond, regardless of which command I call, e.g. code, help, serve, etc. I investigated this a little and found the culprit to be:

<img width="1470" alt="image" src="https://github.com/mila-iqia/milatools/assets/3516539/a5faf423-b6d0-494b-a300-25140fb80403">

`socket.getfqdn` is commonly slow on Mac and solving that [requires some elbow grease](https://apple.stackexchange.com/questions/175320/why-is-my-hostname-resolution-taking-so-long). It can be patched, e.g. via a judicious use of the UNIX `hostname` command. 

Here's a MVP patch: https://github.com/patrickmineault/milatools/commit/aebdc7d0657606e8508eeb6ed7309649c7254f18

**Comment by breuleux** [comment]
Sorry, I'm only now getting to this. Could you create a pull request from that patch?

Also, `hostname -f` and `socket.getfqdn()` actually return different things on my Mac, but as long as they return the same thing on the cluster, which they do, that's fine.

**Comment by breuleux** [comment]
Fixed in #51
