### ISSUE TITLE
Issue running mila code

### ISSUE THREAD

**Issue by ak3ra** [mila-iqia/milatools#50]
### Make sure you can reproduce the issue with the latest version available
```
pip install milatools --upgrade
[milatools command e.g. mila code ...]
```

### What command did you run?
[e.g. `mila code ...`]

### Describe the bug
When I run mila code /path/to/remote_dir, all seems to work but vscode never launches, I get this traceback

See screenshot.

### Desktop (please complete the following information):
 - OS: Mac Os Ventura Version 13.4

### Additional context
![image](https://github.com/mila-iqia/milatools/assets/12105163/f86f779d-4e96-4fa1-97d8-82ac9c9d1ab1)

**Comment by lebrice** [comment]
Also note: Running from `zsh` shell, and running `code` in that terminal gives `zsh: command not found: code`

**Comment by lebrice** [comment]
Seems to now be working on @ak3ra 's side. I suspect that this error might have been fixed by upgrading milatools.

**Comment by ak3ra** [comment]
Issue fixed by adding vscode "code" to path, and upgrading mila-tools
